table Parameter_numeric
	lineageTag: 81a4094d-60a3-4f1d-b2bc-66e36690fea1

	measure 'Parameter_numeric Value' = SELECTEDVALUE('Parameter_numeric'[Parameter_numeric])
		formatString: 0
		lineageTag: 6367f0ce-8e5f-4270-a280-63530376700f

	column Parameter_numeric
		formatString: 0
		lineageTag: a2b13819-373c-4abd-adc4-758696bac564
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Parameter_numeric = calculated
		mode: import
		source = GENERATESERIES(0, 5, 1)

	annotation PBI_Id = 1906c71abb314317b64e880e62b23b9c

